module ESpeakNG
  private class Language
    getter! code : String

    def initialize(lang_name : String)
      @code = LANGUAGES_TO_FFI_MAPPING.fetch(lang_name.downcase, lang_name)
    end

    private LANGUAGES_TO_FFI_MAPPING = {
      afrikaans:   "af",
      amharic:     "am",
      aragonese:   "an",
      arabic:      "ar",
      assamese:    "as",
      azerbaijani: "az",
      bulgarian:   "bg",
      bengali:     "bn",
      bishnupriya_manipuri: "bpy",
      bosnian:     "bs",
      catalan:     "ca",
      chinese_mandarin: "cmn",
      czech:       "cs",
      welsh:       "cy",
      danish:      "da",
      german:      "de",
      greek:       "el",
      english:     "en-gb",
      english_caribbean:     "en-029",
      english_great_britain: "en-gb",
      english_scotland:      "en-gb-scotland",
      english_lancaster:     "en-gb-x-gbclan",
      english_west_midlands: "en-gb-x-gbcwmd",
      english_received_pronunciation: "en-gb-x-rp",
      english_america:       "en-us",
      esperanto:             "eo",
      spanish_spain:         "es",
      spanish_latin_america: "es-419",
      estonian:              "et",
      basque:                "eu",
      persian:               "fa",
      persian_pinglish:      "fa-Latn",
      finnish:               "fi",
      french_belgium:        "fr-be",
      french_switzerland:    "fr-ch",
      french_france:         "fr-fr",
      gaelic_irish:          "ga",
      gaelic_scottish:       "gd",
      guarani:               "gn",
      greek_ancient:         "grc",
      gujarati:              "gu",
      hindi:                 "hi",
      croatian:              "hr",
      hungarian:             "hu",
      armenian_east_armenia: "hy",
      armenian_west_armenia: "hy-arevmda",
      interlingua: "ia",
      indonesian:  "id",
      icelandic:   "is",
      italian:     "it",
      japanese:    "ja",
      lojban:      "jbo",
      georgian:    "ka",
      greenlandic: "kl",
      kanada:      "kn",
      korean:      "ko",
      konkani:     "kok",
      kurdish:     "ku",
      kyrgyz:      "ky",
      latin:       "la",
      lingua_franca_nova: "lfn",
      lithuanian:  "lt",
      latvian:     "lv",
      macedonian:  "mk",
      malayalam:   "ml",
      marathi:     "mr",
      malay:       "ms",
      maltese:     "mt",
      burmese:     "my",
      norwegian_bokmal:  "nb",
      nahuatl_classical: "nci",
      nepali:      "ne",
      dutch:       "nl",
      oromo:       "om",
      oriya:       "or",
      punjabi:     "pa",
      papiamento:  "pap",
      polish:      "pl",
      portuguese_portugal: "pt",
      portuguese_brazil:   "pt-br",
      romanian:    "ro",
      russian:     "ru",
      sindhi:      "sd",
      sinhala:     "si",
      slovak:      "sk",
      slovenian:   "sl",
      albanian:    "sq",
      serbian:     "sr",
      swedish:     "sv",
      swahili:     "sw",
      tamil:       "ta",
      telugu:      "te",
      setswana:    "tn",
      turkish:     "tr",
      tatar:       "tt",
      urdu:        "ur",
      vietnamese_northern: "vi",
      vietnamese_central:  "vi-vn-x-central",
      vietnamese_southern: "vi-vn-x-south",
      chinese_cantonese:   "yue"
    }
  end # class Language
end # module ESpeakNG